version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=36ejokh@vip-*p=@_9et2cvwkm&#4$l)t)jn!+0^ekz@mr$$*(
      - DEBUG=0
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51HLrUwDKzHESJ69CLPcxTv5Thz2POosw5oSj5xYXYVYVd5sy6ZnAn0b0ytoYGXNAGEczYt6qNmXvfuE0mSpQAz5e00fs805vae
      - STRIPE_TEST_SECRET_KEY=sk_test_51HLrUwDKzHESJ69CHrdQCPudP3b47mNRVngq23nuZj5nbeJfpOCpocshREJ2qXNywcHzL4pwNZkNJ1UMDaoHrTPP00GMbPgdKi

    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11

    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

